### ISSUE TITLE
export some default margins

### ISSUE THREAD

**Issue by obartra** [obartra/reflex#131]
- export default margins (e.g. `const item = [0, 0.5, 1]`) or component wrappers that set some defaults (e.g. `const Item = (props) => <Grid margin={[0, 0.5, 1]} {...props} />`)
- add to the wiki https://github.com/obartra/reflex/wiki/Spacing

**Comment by obartra** [comment]
Now that `Col` is provided do we still want to offer a list of "common" margins?

**Comment by obartra** [comment]
@arahansen

**Comment by arahansen** [comment]
My preference would be to avoid doing this. Instead either have more
derived exports, or additional available properties for the existing
components.

Or just leave it to user land 😄

**Comment by obartra** [comment]
agreed, closing
