### ISSUE TITLE
Add dev mode

### ISSUE THREAD

**Issue by arahansen** [obartra/reflex#146]
Dev mode should be enabled when the following is true:
1. Reflex is running in development mode (`process.env.NODE_ENV === 'development'`)
2. Specific key combination is entered by user

`Grid` should take a new `dev` prop of enum type `1 | 2 | 3 | 4` which will assign a background and font color to the grid when dev mode is on.

**Comment by obartra** [comment]
Examples should be updated to use this.

I don't think relfex should have a key combination. Maybe a value that's passed through context and set globally?

**Comment by arahansen** [comment]
yep, I agree. To both points.

**Comment by arahansen** [comment]
@obartra 
A small problem with implementing dev mode via context: When toggling the devMode flag, in context, `React.PureComponent` does not catch this as an update and does not rerender.

Example:
```javascript
<Grid>
  <Grid dev={2}>Text</Grid>
</Grid>
```

Since `Grid` is a PureComponent, it will not allow the inner Grid to rerender when context changes, and the devMode backgrounds will not toggle.

I see two potential solutions here:
1. Use regular old `React.Component` and potentially sacrifice some performance? Although, perhaps there are other downsides to using `PureComponent`? (not sure)
2. Don't use context at all, and instead, set a css class on the `Layout` component currently handling context that will force all children `Grids` to add their respective classes. Downside here, is that the dev class (which would apply colors) would always need to be applied during development which can add noise.

**Comment by obartra** [comment]
I'm fine with either approach.

I like the `React.Component` one because it keeps all the logic in JS and limits the scope of what we do in CSS to simpler logic.

On the flip side, a global css class wouldn't add much noise and may be good enough while being able to keep Grid as PureComponent.

I would not add a class to every component though, that would be a lot of noise, I agree

**Comment by arahansen** [comment]
Closed via #153
