### ISSUE TITLE
Webpack Includes `eval` check in dist

### ISSUE THREAD

**Issue by arahansen** [obartra/reflex#175]
When bundling, webpack is including an `eval` check to see if its available.

This causes a warning for servers that have no eval CSP settings enabled.

We should explore if it's possible to remove this eval from the bundle to remove this console warning.

**Comment by arahansen** [comment]
Code in question:

```
try {
	// This works if eval is allowed (see CSP)
	g = g || Function("return this")() || (1, eval)("this");
} catch (e) {
	// This works if the window reference is available
	if ((typeof window === "undefined" ? "undefined" : _typeof(window)) === "object") g = window;
}
```

**Comment by obartra** [comment]
Yeah it's annoying. It causes it to report the issue but it wouldn't break anything since it's just testing if CSP is enabled or not. I don't know if I would count it as an issue though

**Comment by obartra** [comment]
Also, could this be related to the sourcemaps? I'm wondering if this happens with the prod build

**Comment by obartra** [comment]
This is the offending file https://github.com/webpack/webpack/blob/master/buildin/global.js

**Comment by obartra** [comment]
Looks like redux is not using webpack anymore but when upgraded to webpack 2 this is how they tackled it: https://github.com/reactjs/react-redux/pull/680/files#diff-11e9f7f953edc64ba14b0cc350ae7b9dR20
