### ISSUE TITLE
generateCssFlow should recursively walk the dist folder for css files

### ISSUE THREAD

**Issue by arahansen** [obartra/reflex#239]
[generateCssFlow](https://github.com/obartra/reflex/blob/master/scripts/generateCssFlow.js) currently only looks at the top level dist folder for css files to mock out for flow typing.

There are now css files in the derived folder. These need to be mocked out as well. So the script should recursively walk through the entire dist subtree to mock all possible css files.

**Comment by obartra** [comment]
This is not fixed, reopening

**Comment by obartra** [comment]
I just ran this and it seems to be working well. It doesn't flatten the directory structure but it generates types for `derived/root.css` which is the only css file in `derived`. was this all that was needed?

**Comment by arahansen** [comment]
I was just thinking about this, and was thinking maybe we could add the [webpack plugin](https://github.com/skovhus/css-modules-flow-types) we use internally at Axon to accomplish what this script is doing, and in a more robust manner.

**Comment by obartra** [comment]
Yeah that would be great!

**Comment by arahansen** [comment]
not needed anymore since we no longer ship css for reflex
