### ISSUE TITLE
Cannot access Grid as a ref

### ISSUE THREAD

**Issue by garretto** [obartra/reflex#255]
Grid is declared as a functional component, so `c` is `null` in the below example.

```javascript
<Grid ref={c => this.myRef = c} />
```
More info:
https://facebook.github.io/react/docs/refs-and-the-dom.html#refs-and-functional-components

**Comment by obartra** [comment]
would you be able to use `gridHoc` instead for that? that would give you access to the underlying ref

**Comment by arahansen** [comment]
This can be accomplished with a one-liner:

`const GridWithRef = GridHoc(props => <div {...props} ref={props.innerRef} />)`

then accessed with:

`<GridWithRef innerRef={ref => console.log(ref) /> // ref to div`

**Comment by garretto** [comment]
Cool that works, thanks!
