### ISSUE TITLE
Refactor Build Process

### ISSUE THREAD

**Issue by arahansen** [obartra/reflex#36]
flexgrid was originally intended as a pure css solution. Thus has a build system to accommodate such a solution. We should upgrade the build pipeline to take into account the new component-driven nature 

- [ ] Add generalized, production-ready build rather than only Storybook-centric
- [ ] Ensure lodash is code split properly
- [ ] Webpack build should extract JS into standalone min bundle for user consumption by users
- [ ] Add flowtype checks as part as build process
- [ ] Generate flow types and output to dist using something like [flow-copy-source](https://github.com/AgentME/flow-copy-source)

**Comment by obartra** [comment]
Looks good but the webpack build for storybook is needed. We just need an independent one for publication

**Comment by arahansen** [comment]
The two should be sharing many, if not, most config options, correct?

**Comment by obartra** [comment]
Unless they updated it, Storybook uses webpack 1. The current setup also relies on storybook extending the webpack config. I think it's better if we use our own since that one is purely meant as configuration for storybook
