### ISSUE TITLE
Show Documentation and Implementations Details in storybook

### ISSUE THREAD

**Issue by arahansen** [obartra/reflex#44]
Storybook has addon configurations available for showing the code used for a given story.

It can also show the props available to pass in to a component.

These would be beneficial for showing how these layout systems work at a glance.

**Comment by obartra** [comment]
I tried 2 plugins that were supposed to do it but I wasn't able to get it to work with HOC, It just listed everything as 'Component' even when setting display Name.

👍 if you get them to work

**Comment by obartra** [comment]
Is this complete now with the JSX plugin or do you want to document all props as well?

**Comment by arahansen** [comment]
This can be closed since we now have implementation details within Storybook.

See https://github.com/obartra/reflex/issues/80 for additional documentation needs.
