### ISSUE TITLE
What Should We Call This Library?

### ISSUE THREAD

**Issue by arahansen** [obartra/reflex#61]
There are two hard things in programming:
- Naming Things
- ... something else nobody really cares about

Thus, we are looking for suggestions on what this library should be called.

A few things to keep in mind in potential names:
- in some way reflects the purpose of the library
- easy to spell and easy to find
- doesn't conflict with existing libraries

## Current options:
- reflex-layout
- flexor

**Comment by obartra** [comment]
Let's go with "Reflex" and we'll figure out the npm package name later

We should also have a 1 or 2 emojis that describe it and a moto.

For moto I suggest ""Flexbox React layout system"
